extends Node

var weapons: Array = []
var gifts: Array = []
var player_weapons: Array = []
var player_accessories: Array = []
var player_bullets: Array = []
var current_character: Dictionary = {}
var current_character_id := ""
var current_weapon: Dictionary = {}
var current_weapon_id := ""
var exp_level := 1
var permanent_upgrade_snapshot = null
var player_max_hp := 100
var player_hp := 100
var mini_humidifier_level := 0
var mini_humidifier_timer := 0.0
var mini_humidifier_hurt_cooldown := 0.0
var equipment_weapon_timers: Dictionary = {}
var boomerang_hits: Dictionary = {}
var hit_fx: Array = []
var enemies: Array = []
var lastWeaponRuntimeCleanupReason := ""
var mental_care_level := 0
var equipment_damage_rate := 1.0
var equipment_range_rate := 1.0
var equipment_interval_rate := 1.0
var equipment_bullet_support_level := 0
var notification_bell_level := 0
var hammer_damage := 0.0
var hammer_range := 0.0
var hammer_interval := 0.0
var knockback_power := 0.0
var player_speed := 0.0
var dash_cooldown := 0.0
var comment_radar_level := 0
var comment_radar_range_bonus := 0.0
var item_magnet_speed_rate := 1.0
var magnet_range := 0.0
var sweet_tooth_level := 0
var superchat_level := 0
var boomerang_level := 0
var gifts_taken := 0
var taken_gift_names: Array = []
var offered_gifts: Array = []
var gift_hype := 0
var max_gift_hype := 0
var state := "gift_choice"
var pause_reasons: Array = ["GiftSelection"]
